### ISSUE TITLE
Error after initial start of the application (404 Not Found)

### ISSUE THREAD

**Issue by schminkel** [HoudiniGraphql/intro#18]
Following the "Get Started" on https://houdinigraphql.com/intro the application did not to work properly after initial start.

```
npx degit houdinigraphql/intro hello-houdini
cd hello-houdini
npm i
npm run dev

node -v (v18.16.0)
open  http://localhost:5173/
```

Error: Not found: /
    at resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:394:13)
    at resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:243:5)
    at #options.hooks.handle (/node_modules/@sveltejs/kit/src/runtime/server/index.js:41:55)
    at Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:240:40)
Error: Not found: /
    at resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:394:13)
    at resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:243:5)
    at #options.hooks.handle (/node_modules/@sveltejs/kit/src/runtime/server/index.js:41:55)
    at Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:240:40)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

<img width="985" alt="image" src="https://github.com/HoudiniGraphql/intro/assets/5998952/359f11b8-d9fa-4665-92db-de93e432afac">

**Thanks for your support!**

**Comment by kasparpalgi** [comment]
500 Internal Error for me at http://localhost:5173/6

**Comment by kasparpalgi** [comment]
Ah, didn't chech that should use the [final branch](https://github.com/HoudiniGraphql/intro/tree/final). That one gives me more detailed error:

```
SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at Proxy.eval (/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:286:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async eval (/@fs/C:/git/course/houdini-pokemon-final/$houdini/runtime/client/plugins/fetch.js:62:12)
    at async network (/@fs/C:/git/course/houdini-pokemon-final/$houdini/runtime/client/plugins/fetch.js:23:24)
```

**Comment by kasparpalgi** [comment]
I suspect it was API issue. As I don't know the test API used, I just connected to my Hasura GraphQL API endpoint and worked well.
